version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly

  # Maintain dependencies for Helm
  - package-ecosystem: docker
    directory: /charts/monica
    schedule:
      interval: weekly
