# Required
input:
  - charts/monica/values.yaml

indent: 2
output: charts/monica/values.schema.json

schemaRoot:
  id: https://monicahq.github.io/helm/schema
  title: Monica Helm Charts Values Schema
  description: Schema for Helm values
  additionalProperties: true
