{{- if .Values.hpa.enabled }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "monica.fullname" . }}
  labels:
    {{- include "monica.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "monica.fullname" . }}
  {{- with .Values.hpa }}
  minReplicas: {{ .minPods }}
  maxReplicas: {{ .maxPods }}
  targetCPUUtilizationPercentage: {{ .cputhreshold }}
  {{- end }}
{{- end }}
