{{- if .Values.ingress.enabled }}
---
apiVersion: {{ include "monica.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "monica.fullname" . }}
  labels:
    {{- include "monica.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
    {{- with .Values.ingress.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - {{- with .Values.monica.host }}
      host: {{ . }}
      {{- end }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            {{- if eq (include "monica.ingress.apiVersion" $) "networking.k8s.io/v1" }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend:
              {{- if eq (include "monica.ingress.apiVersion" $) "networking.k8s.io/v1" }}
              service:
                name: {{ template "monica.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
              {{- else }}
              serviceName: {{ template "monica.fullname" . }}
              servicePort: {{ .Values.service.port }}
              {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
