{{- if .Values.nginx.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "monica.fullname" . }}-publicdir
  labels:
    {{- include "monica.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
{{- end -}}
