{{- if .Values.nginx.enabled }}
---
kind: Job
apiVersion: batch/v1
metadata:
  name: {{ template "monica.fullname" . }}-init
  labels:
    {{- include "monica.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ template "monica.fullname" . }}-init
      labels:
        {{- include "monica.labels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: monica-nginx-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - {{ .Files.Get "files/init-publicdir.sh" | quote }}
          volumeMounts:
            - name: monica-publicdir
              mountPath: /public
      restartPolicy: Never
      volumes:
        - name: monica-publicdir
          persistentVolumeClaim:
            claimName: {{ template "monica.fullname" . }}-publicdir
{{- end }}
