{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "monica.fullname" . }}-privileged
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - extensions
    resourceNames:
      - privileged
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "monica.fullname" . }}-privileged
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "monica.fullname" . }}-privileged
subjects:
  - kind: ServiceAccount
    name: {{ include "monica.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
