{{- if not .Values.monica.existingSecret.enabled }}
{{- $keyprevious := lookup "v1" "Secret" .Release.Namespace "appkey" }}
{{- $appkey := "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "monica.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "monica.name" . }}
    helm.sh/chart: {{ include "monica.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if $keyprevious }}
  appkey: {{ ( index $keyprevious.data "appkey" ) }}
  {{- else }}
  {{- $appkey = randAlphaNum 32 }}
  appkey: {{ $appkey | b64enc }}
  {{- end }}
  {{- if .Values.monica.mail.enabled }}
  smtp-username: {{ default "" .Values.monica.mail.smtp.name | b64enc | quote }}
  smtp-password: {{ default "" .Values.monica.mail.smtp.password | b64enc | quote }}
  {{- end }}  
{{- end }}
