---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "monica.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "monica.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  selector:
    {{- include "monica.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  type: {{ .Values.service.type }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerClass }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.nginx.enabled }}
      targetPort: {{ .Values.nginx.containerPort | default 80 }}
      {{- else }}
      targetPort: {{ .Values.monica.containerPort | default 80 }}
      {{- end }}
      protocol: TCP
      name: http
      {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      {{- end }}
