apiVersion: v1
kind: Service
metadata:
  name: {{ template "monica.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "monica.name" . }}
    helm.sh/chart: {{ include "monica.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ default "" .Values.service.nodePort}}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "monica.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
