apiVersion: v1
kind: Service
metadata:
  name: {{ template "monica.fullname" . }}
  labels:
    {{- include "monica.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ default "" .Values.service.nodePort}}
    {{- end }}
  selector:
    {{- include "monica.selectorLabels" . | nindent 4 }}
