name: Helm docs

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  helm: v3.16.2

jobs:
  docs:
    name: Helm docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1

      - name: Check if there is any file update needed
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo -e "Waiting modifications:\n$status"
            echo "::error::Changes waiting. Please run 'helm-docs' prior to your next commit."
            exit -1
          fi

  schema:
    name: Generate schema file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.helm }}

      - name: Generate schema file
        uses: losisin/helm-values-schema-json-action@v1
        with:
          input: charts/monica/values.yaml
          output: charts/monica/values.schema.json
          indent: 2
          fail-on-diff: true
